### ISSUE TITLE
Not Working on dieverdammten.de

### ISSUE THREAD

**Issue by DavidG2604** [Ryder-One/hmap#7]
The Map does not work on dieverdammten.de, while working on the other games (tested zombinoia and die2nite).

Was testing on Chrome 80 and Tampermonkey 4.9 on Chrome.
This is what the Browser Console tells me: 
http://prntscr.com/rj96m4

**Comment by Ryder-One** [comment]
Thank you for your report, I'll dig into that as soon as I have the time to do so.

Don't worry if you don't have news, I'm not forgetting this ;)

**Comment by Ludofloria** [comment]
I've just fixed it with my PR 12 ;)
